#!/bin/bash -xe
# Dockerhub build script
installer_url="https://github.com/rojopolis/thinkbox-deadline-client/releases/download/10.0.15.5/DeadlineClient-10.0.15.5-linux-x64-installer.run"
curl -OL $installer_url
installer="*.run"
chmod +x $installer
docker build --build-arg DEADLINE_INSTALLER=$installer -t $IMAGE_NAME .
